defaults: &defaults
  secret_key: sk_test_dIhhceoA3DHS6hh4NMMgh9Md
  basic: 1
   

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  secret_key: sk_live_1nxB5DbW3gtzjRWiOLVnVVzT
  basic: 1