INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('8','ALL','Lek','Lek');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('12','DZD','Algerian Dinar',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('32','ARS','Argentine Peso','$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('36','AUD','Australian Dollar','$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('44','BSD','Bahamian Dollar','$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('48','BHD','Bahraini Dinar',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('50','BDT','Bangladeshi Taka',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('51','AMD','Armenian Dram',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('52','BBD','Barbados Dollar','$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('60','BMD','Bermudian Dollar','$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('64','BTN','Ngultrum',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('68','BOB','Boliviano','$b');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('72','BWP','Pula','P');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('84','BZD','Belize Dollar','BZ$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('90','SBD','Solomon Islands Dollar','$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('96','BND','Brunei Dollar','$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('104','MMK','Kyat',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('108','BIF','Burundian Franc',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('116','KHR','Riel','&#6107;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('124','CAD','Canadian Dollar','$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('132','CVE','Cape Verde Escudo',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('136','KYD','Cayman Islands Dollar','$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('144','LKR','Sri Lanka Rupee','&#8360;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('152','CLP','Chilean Peso','$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('156','CNY','Yuan Renminbi','&#20803;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('170','COP','Colombian Peso','$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('174','KMF','Comoro Franc',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('188','CRC','Costa Rican Colon','&#8353;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('191','HRK','Croatian Kuna','kn');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('192','CUP','Cuban Peso','&#8369;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('196','CYP','Cyprus Pound','&#163;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('203','CZK','Czech Koruna','K&#269;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('208','DKK','Danish Krone','kr');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('214','DOP','Dominican Peso','RD$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('230','ETB','Ethiopian Birr',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('232','ERN','Nakfa',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('233','EEK','Kroon','kr');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('238','FKP','Falkland Islands Pound','&#163;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('242','FJD','Fiji Dollar','$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('262','DJF','Djibouti Franc',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('270','GMD','Dalasi',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('288','GHS','Cedi',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('292','GIP','Gibraltar pound','&#163;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('320','GTQ','Quetzal','Q');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('324','GNF','Guinea Franc',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('328','GYD','Guyana Dollar','$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('332','HTG','Haiti Gourde',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('340','HNL','Lempira','L');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('344','HKD','Hong Kong Dollar','HK$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('348','HUF','Forint','Ft');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('352','ISK','Iceland Krona','kr');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('356','INR','Indian Rupee','&#8360;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('360','IDR','Rupiah','Rp');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('364','IRR','Iranian Rial','&#65020;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('368','IQD','Iraqi Dinar',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('376','ILS','New Israeli Shekel','&#8362;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('388','JMD','Jamaican Dollar','J$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('392','JPY','Japanese yen','&#165;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('398','KZT','Tenge','&#1083;&#1074;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('400','JOD','Jordanian Dinar',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('404','KES','Kenyan Shilling',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('408','KPW','North Korean Won','&#8361;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('410','KRW','South Korean Won','&#8361;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('414','KWD','Kuwaiti Dinar',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('417','KGS','Som','&#1083;&#1074;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('418','LAK','Kip','&#8365;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('422','LBP','Lebanese Pound','&#163;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('426','LSL','Loti',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('428','LVL','Latvian Lats','Ls');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('430','LRD','Liberian Dollar','$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('434','LYD','Libyan Dinar',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('440','LTL','Lithuanian Litas','Lt');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('446','MOP','Pataca',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('454','MWK','Kwacha',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('458','MYR','Malaysian Ringgit','RM');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('462','MVR','Rufiyaa',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('470','MTL','Maltese Lira','Lm');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('478','MRO','Ouguiya',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('480','MUR','Mauritius Rupee','&#8360;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('484','MXN','Mexican Peso','$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('496','MNT','Tugrik','&#8366;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('498','MDL','Moldovan Leu',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('504','MAD','Moroccan Dirham',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('512','OMR','Rial Omani','&#65020;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('516','NAD','Namibian Dollar','$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('524','NPR','Nepalese Rupee','&#8360;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('532','ANG','Netherlands Antillian Guilder','&#402;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('533','AWG','Aruban Guilder','&#402;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('548','VUV','Vatu',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('554','NZD','New Zealand Dollar','$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('558','NIO','Cordoba Oro','C$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('566','NGN','Naira','&#8358;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('578','NOK','Norwegian Krone','kr');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('586','PKR','Pakistan Rupee','&#8360;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('590','PAB','Balboa','B/.');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('598','PGK','Kina',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('600','PYG','Guarani','Gs');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('604','PEN','Nuevo Sol','S/.');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('608','PHP','Philippine Peso','Php');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('634','QAR','Qatari Rial','&#65020;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('643','RUB','Russian Ruble','&#1088;&#1091;&#1073;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('646','RWF','Rwanda Franc',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('654','SHP','Saint Helena Pound','&#163;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('678','STD','Dobra',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('682','SAR','Saudi Riyal','&#65020;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('690','SCR','Seychelles Rupee','&#8360;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('694','SLL','Leone',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('702','SGD','Singapore Dollar','$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('703','SKK','Slovak Koruna','SIT');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('704','VND','Vietnamese dong','&#8363;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('706','SOS','Somali Shilling','S');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('710','ZAR','South African Rand','R');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('716','ZWD','Zimbabwe Dollar','Z$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('748','SZL','Lilangeni',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('752','SEK','Swedish Krona','kr');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('756','CHF','Swiss Franc','CHF');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('760','SYP','Syrian Pound','&#163;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('764','THB','Baht','&#3647;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('776','TOP','Pa\'anga',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('780','TTD','Trinidad and Tobago Dollar','TT$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('784','AED','United Arab Emirates Dirham',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('788','TND','Tunisian Dinar',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('795','TMM','Manat',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('800','UGX','Uganda Shilling',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('807','MKD','Denar','&#1076;&#1077;&#1085;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('818','EGP','Egyptian Pound','&#163;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('826','GBP','Pound Sterling','&#163;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('834','TZS','Tanzanian Shilling',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('840','USD','US Dollar','$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('858','UYU','Peso Uruguayo','$U');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('860','UZS','Uzbekistan Som','&#1083;&#1074;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('862','VEB','Venezuelan bolivar','Bs');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('882','WST','Samoan Tala',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('886','YER','Yemeni Rial','&#65020;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('894','ZMK','Kwacha',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('901','TWD','New Taiwan Dollar','NT$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('938','SDG','Sudanese Pound',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('941','RSD','Serbian Dinar','&#1044;&#1080;&#1085;.');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('943','MZN','Metical','MT');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('944','AZN','Azerbaijanian Manat','&#1084;&#1072;&#1085;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('946','RON','Romanian New Leu','lei');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('949','TRY','New Turkish Lira','YTL');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('968','SRD','Surinam Dollar','$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('969','MGA','Malagasy Ariary',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('970','COU','Unidad de Valor Real',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('971','AFN','Afghani','&#1547;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('972','TJS','Somoni',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('973','AOA','Kwanza',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('974','BYR','Belarussian Ruble','p.');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('975','BGN','Bulgarian Lev','&#1083;&#1074;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('976','CDF','Franc Congolais',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('977','BAM','Convertible Marks','KM');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('978','EUR','Euro','&#8364;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('979','MXV','Mexican Unidad de Inversion (UDI) (Funds code)',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('980','UAH','Hryvnia','&#8372;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('981','GEL','Lari',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('984','BOV','Bolivian Mvdol (Funds code)',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('985','PLN','Zloty','z&#322;');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('986','BRL','Brazilian Real','R$');
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('990','CLF','Unidades de formento (Funds code)',NULL);
INSERT INTO `currencies` (`id`,`code`,`name`,`html_symbol`) VALUES ('999','XXX','No Currency','&curren;');


